# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ticket_booking_pb2 as ticket__booking__pb2


class TicketBookingServiceStub(object):
    """Client to Application Server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/ticketbooking.TicketBookingService/Login',
                request_serializer=ticket__booking__pb2.LoginRequest.SerializeToString,
                response_deserializer=ticket__booking__pb2.LoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/ticketbooking.TicketBookingService/Logout',
                request_serializer=ticket__booking__pb2.LogoutRequest.SerializeToString,
                response_deserializer=ticket__booking__pb2.StatusResponse.FromString,
                )
        self.Post = channel.unary_unary(
                '/ticketbooking.TicketBookingService/Post',
                request_serializer=ticket__booking__pb2.PostRequest.SerializeToString,
                response_deserializer=ticket__booking__pb2.StatusResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/ticketbooking.TicketBookingService/Get',
                request_serializer=ticket__booking__pb2.GetRequest.SerializeToString,
                response_deserializer=ticket__booking__pb2.GetResponse.FromString,
                )
        self.GetLLMAssistance = channel.unary_unary(
                '/ticketbooking.TicketBookingService/GetLLMAssistance',
                request_serializer=ticket__booking__pb2.LLMRequest.SerializeToString,
                response_deserializer=ticket__booking__pb2.LLMResponse.FromString,
                )


class TicketBookingServiceServicer(object):
    """Client to Application Server
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLLMAssistance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketBookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=ticket__booking__pb2.LoginRequest.FromString,
                    response_serializer=ticket__booking__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=ticket__booking__pb2.LogoutRequest.FromString,
                    response_serializer=ticket__booking__pb2.StatusResponse.SerializeToString,
            ),
            'Post': grpc.unary_unary_rpc_method_handler(
                    servicer.Post,
                    request_deserializer=ticket__booking__pb2.PostRequest.FromString,
                    response_serializer=ticket__booking__pb2.StatusResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=ticket__booking__pb2.GetRequest.FromString,
                    response_serializer=ticket__booking__pb2.GetResponse.SerializeToString,
            ),
            'GetLLMAssistance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLLMAssistance,
                    request_deserializer=ticket__booking__pb2.LLMRequest.FromString,
                    response_serializer=ticket__booking__pb2.LLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticketbooking.TicketBookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TicketBookingService(object):
    """Client to Application Server
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticketbooking.TicketBookingService/Login',
            ticket__booking__pb2.LoginRequest.SerializeToString,
            ticket__booking__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticketbooking.TicketBookingService/Logout',
            ticket__booking__pb2.LogoutRequest.SerializeToString,
            ticket__booking__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticketbooking.TicketBookingService/Post',
            ticket__booking__pb2.PostRequest.SerializeToString,
            ticket__booking__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticketbooking.TicketBookingService/Get',
            ticket__booking__pb2.GetRequest.SerializeToString,
            ticket__booking__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLLMAssistance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticketbooking.TicketBookingService/GetLLMAssistance',
            ticket__booking__pb2.LLMRequest.SerializeToString,
            ticket__booking__pb2.LLMResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class InternalServiceStub(object):
    """Internal Application Server to Application Server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessBusinessRequest = channel.unary_unary(
                '/ticketbooking.InternalService/ProcessBusinessRequest',
                request_serializer=ticket__booking__pb2.BusinessRequest.SerializeToString,
                response_deserializer=ticket__booking__pb2.BusinessResponse.FromString,
                )
        self.SyncState = channel.unary_unary(
                '/ticketbooking.InternalService/SyncState',
                request_serializer=ticket__booking__pb2.StateRequest.SerializeToString,
                response_deserializer=ticket__booking__pb2.StateResponse.FromString,
                )


class InternalServiceServicer(object):
    """Internal Application Server to Application Server
    """

    def ProcessBusinessRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessBusinessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBusinessRequest,
                    request_deserializer=ticket__booking__pb2.BusinessRequest.FromString,
                    response_serializer=ticket__booking__pb2.BusinessResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=ticket__booking__pb2.StateRequest.FromString,
                    response_serializer=ticket__booking__pb2.StateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticketbooking.InternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InternalService(object):
    """Internal Application Server to Application Server
    """

    @staticmethod
    def ProcessBusinessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticketbooking.InternalService/ProcessBusinessRequest',
            ticket__booking__pb2.BusinessRequest.SerializeToString,
            ticket__booking__pb2.BusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ticketbooking.InternalService/SyncState',
            ticket__booking__pb2.StateRequest.SerializeToString,
            ticket__booking__pb2.StateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
